from __future__ import annotations

from typing import Any

from ggmlc.ir.op import OpCode

# Map ATen Target -> (OpCode, attribute_extractor)
ATEN_OP_MAP: dict[str, OpCode] = {
    "aten.add.Tensor": OpCode.ADD,
    "aten.add.Scalar": OpCode.ADD,
    "aten.add_.Tensor": OpCode.ADD,
    "aten.add_.Scalar": OpCode.ADD,
    "aten.sub.Tensor": OpCode.SUB,
    "aten.sub.Scalar": OpCode.SUB,
    "aten.sub_.Tensor": OpCode.SUB,
    "aten.subtract.Tensor": OpCode.SUB,
    "aten.subtract.Scalar": OpCode.SUB,
    "aten.subtract_.Tensor": OpCode.SUB,
    "aten.subtract_.Scalar": OpCode.SUB,
    "aten.rsub.Tensor": OpCode.SUB,
    "aten.rsub.Scalar": OpCode.SUB,
    "aten.mul.Tensor": OpCode.MUL,
    "aten.mul.Scalar": OpCode.MUL,
    "aten.mul_.Tensor": OpCode.MUL,
    "aten.prod.default": OpCode.MUL,
    "aten.div.Tensor": OpCode.DIV,
    "aten.div.Scalar": OpCode.DIV,
    "aten.div_.Tensor": OpCode.DIV,
    "aten.neg.default": OpCode.NEG,
    "aten.sqrt.default": OpCode.SQRT,
    "aten.rsqrt.default": OpCode.RSQRT,
    "aten.exp.default": OpCode.EXP,
    "aten.log.default": OpCode.LOG,
    "aten.abs.default": OpCode.ABS,
    "aten.maximum.default": OpCode.MAXIMUM,
    "aten.minimum.default": OpCode.MINIMUM,
    "aten.amax.default": OpCode.AMAX,
    "aten.amin.default": OpCode.AMIN,
    "aten.amax.dim_IntList": OpCode.AMAX,
    "aten.amin.dim_IntList": OpCode.AMIN,
    "aten.amax.dim": OpCode.AMAX,
    "aten.argmax.default": OpCode.ARGMAX,
    "aten.argmax.dim": OpCode.ARGMAX,
    "aten.argmax": OpCode.ARGMAX,
    "aten.relu.default": OpCode.RELU,
    "aten.relu_.default": OpCode.RELU,
    "aten.relu6.default": OpCode.CLAMP,
    "aten.relu6_.default": OpCode.CLAMP,
    "aten.gelu.default": OpCode.GELU,
    "aten.silu.default": OpCode.SILU,
    "aten.silu_.default": OpCode.SILU,
    "aten.sigmoid.default": OpCode.SIGMOID,
    "aten.sigmoid_.default": OpCode.SIGMOID,
    "aten.hardswish.default": OpCode.HARDSWISH,
    "aten.hardswish_.default": OpCode.HARDSWISH,
    "aten.hardsigmoid.default": OpCode.HARDSIGMOID,
    "aten.hardsigmoid_.default": OpCode.HARDSIGMOID,
    "aten.clamp.default": OpCode.CLAMP,
    "aten.clamp.Tensor": OpCode.CLAMP,
    "aten.clamp_.default": OpCode.CLAMP,
    "aten.clamp_min.default": OpCode.CLAMP,
    "aten.clamp_max.default": OpCode.CLAMP,
    "aten.hardtanh.default": OpCode.CLAMP,
    "aten.hardtanh_.default": OpCode.CLAMP,
    "aten.tanh.default": OpCode.TANH,
    "aten.sin.default": OpCode.SIN,
    "aten.cos.default": OpCode.COS,
    "aten._softmax.default": OpCode.SOFTMAX,
    "aten.softmax.int": OpCode.SOFTMAX,
    "aten.mm.default": OpCode.MATMUL,
    "aten.bmm.default": OpCode.MATMUL,
    "aten.matmul.default": OpCode.MATMUL,
    "aten.linear.default": OpCode.LINEAR,
    "aten.addmm.default": OpCode.LINEAR,
    "aten.embedding.default": OpCode.EMBEDDING,
    "aten.index.Tensor": OpCode.EMBEDDING,
    "aten.view.default": OpCode.VIEW,
    "aten._unsafe_view.default": OpCode.VIEW,
    "aten.reshape.default": OpCode.RESHAPE,
    "aten.flatten.using_ints": OpCode.VIEW,
    "aten.flatten.default": OpCode.VIEW,
    "aten.unflatten.int": OpCode.VIEW,
    "aten.unflatten.default": OpCode.VIEW,
    "aten.permute.default": OpCode.PERMUTE,
    "aten.transpose.int": OpCode.TRANSPOSE,
    "aten.t.default": OpCode.TRANSPOSE,
    "aten.numpy_T.default": OpCode.TRANSPOSE,
    "aten.slice.Tensor": OpCode.SLICE,
    "aten.cat.default": OpCode.CONCAT,
    "aten.split.Tensor": OpCode.SPLIT,
    "aten.expand.default": OpCode.EXPAND,
    "aten.squeeze.dim": OpCode.SQUEEZE,
    "aten.unsqueeze.default": OpCode.UNSQUEEZE,
    "aten.sum.dim_IntList": OpCode.SUM,
    "aten.mean.dim": OpCode.MEAN,
    "aten.scaled_dot_product_attention.default": OpCode.SDPA,
    "aten.native_layer_norm.default": OpCode.LAYER_NORM,
    "aten.layer_norm.default": OpCode.LAYER_NORM,
    "aten.rms_norm.default": OpCode.RMS_NORM,
    "aten.contiguous.default": OpCode.CONTIGUOUS,
    "aten.pow.Tensor_Scalar": OpCode.POW,
    "aten.convolution.default": OpCode.CONV2D,
    "aten.conv2d.default": OpCode.CONV2D,
    "aten.conv1d.default": OpCode.CONV2D,
    "aten.max_pool2d_with_indices.default": OpCode.MAX_POOL2D,
    "aten.max_pool2d.default": OpCode.MAX_POOL2D,
    "aten.avg_pool2d.default": OpCode.AVG_POOL2D,
    "aten.adaptive_avg_pool2d.default": OpCode.ADAPTIVE_AVG_POOL2D,
    "aten.arange.default": OpCode.ARANGE,
    "aten.arange.start": OpCode.ARANGE,
    "aten.repeat_interleave.self_int": OpCode.REPEAT,
    "aten.repeat.default": OpCode.REPEAT,
    "aten.select.int": OpCode.SLICE,
    "aten.batch_norm.default": OpCode.BATCH_NORM,
    "aten._native_batch_norm_legit_no_training.default": OpCode.BATCH_NORM,
    "aten.native_batch_norm.default": OpCode.BATCH_NORM,
    "aten.gather.default": OpCode.GATHER,
    "aten.pad.default": OpCode.PAD,
    "aten.pad": OpCode.PAD,
    "aten.type_as.default": OpCode.CAST,
    "aten._to_copy.default": OpCode.CAST,
    "aten.to.dtype": OpCode.CAST,
}


def get_opcode_for_aten(target: Any) -> OpCode | None:
    name = str(target)
    if name in ATEN_OP_MAP:
        return ATEN_OP_MAP[name]
    # Fallback to string name matching
    for k, v in ATEN_OP_MAP.items():
        if k in name:
            return v
    return None
